# Generated by Django 5.2.6 on 2025-09-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_report", models.TextField()),
                ("drug", models.CharField(blank=True, max_length=255)),
                ("adverse_events", models.JSONField(blank=True, default=list)),
                ("severity", models.CharField(blank=True, max_length=32)),
                ("outcome", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
